// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2is7d74GQy7peJIC4oA-qPp_o-uke2k4',
    appId: '1:88121764633:web:0b89244c57fe730c14f388',
    messagingSenderId: '88121764633',
    projectId: 'tubes-371b7',
    authDomain: 'tubes-371b7.firebaseapp.com',
    storageBucket: 'tubes-371b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4TEPHBQlCY9V1UwvNiwaos2NfqA7EhxY',
    appId: '1:88121764633:android:e5aa59afd189132214f388',
    messagingSenderId: '88121764633',
    projectId: 'tubes-371b7',
    storageBucket: 'tubes-371b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUC3C-YR8KYsgfHG4Nl3EUVLFIUyes2Fs',
    appId: '1:88121764633:ios:9f3fefd1d714203a14f388',
    messagingSenderId: '88121764633',
    projectId: 'tubes-371b7',
    storageBucket: 'tubes-371b7.firebasestorage.app',
    iosBundleId: 'com.example.mobileTubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUC3C-YR8KYsgfHG4Nl3EUVLFIUyes2Fs',
    appId: '1:88121764633:ios:9f3fefd1d714203a14f388',
    messagingSenderId: '88121764633',
    projectId: 'tubes-371b7',
    storageBucket: 'tubes-371b7.firebasestorage.app',
    iosBundleId: 'com.example.mobileTubes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2is7d74GQy7peJIC4oA-qPp_o-uke2k4',
    appId: '1:88121764633:web:7c69a9a61c68fec214f388',
    messagingSenderId: '88121764633',
    projectId: 'tubes-371b7',
    authDomain: 'tubes-371b7.firebaseapp.com',
    storageBucket: 'tubes-371b7.firebasestorage.app',
  );
}
